# Mapping our mods/name/role/roleTerms to Invenio roles
# ! NOTE cast terms to LOWERCASE before using this map. Our metadata is inconsistent between title case and lowercase.
# MODS (which uses MARC list): https://www.loc.gov/marc/relators/relaterm.html
# Invenio roles: https://github.com/inveniosoftware/invenio-rdm-records/blob/master/invenio_rdm_records/fixtures/data/vocabularies/roles.yaml
# contactperson, datacollector, datacurator, datamanager, distributor, editor, hostinginstitution, other, producer, projectleader, projectmanager, projectmember, registrationagency, registrationauthority, relatedperson, researchgroup, researcher, rightsholder, sponsor, supervisor, workpackageleader
# ? Can we add our roles to the Invenio vocab? They're missing a lot.
role_map = {
    "academic partner": "",
    "architect": "",
    "artist": "",
    "associated name": "",
    "author": "",
    "author of introduction, etc.": "",
    "book designer": "",
    "bookjacket designer": "",
    "calligrapher": "",
    "cinematographer": "",
    "collaborator": "",
    "compiler": "",
    "creator": "",
    "curator": "",
    "curator assistant": "",
    "designer": "",
    "editor": "editor",
    "founder": "",
    "illustrator": "",
    "installation artist": "",
    "instructor assistant": "",
    "instructor/curator": "",
    "interviewee": "",
    "interviewer": "",
    "manufacturer": "",
    "minute taker": "",
    "narrator": "",
    "organizer": "",
    "organizer of meeting": "",
    "painter": "",
    "performance artist": "",
    "performer": "",
    "photographer": "",
    "platemaker": "",
    "poet": "",
    "printer": "",
    "printmaker": "",
    "producer": "",
    "professor": "",
    "publisher": "",
    "recording engineer": "",
    "researcher": "researcher",
    "reviewer": "",
    "sculptor": "",
    "singer songwriter": "",
    "speaker": "",
    "teacher": "",
    "transcriber": "",
    "writer": "",
}
